### PR TITLE
Throw error on deployment failure

### PR DESCRIPTION
**Pull request by uschek**
Hi Jens,

it would be useful to check if the deployment was successful. With this PR, it is possible to do something like this:

```js
const result = await sfccDeploy(config);

if (result) {
 // Deployment was successful
} else {
 // Deployment was not successful
}
```

A more advanced approach would be to reject the Promise in case of an error.

### CODE REVIEW

**Comment by jenssimon** [comment]
Hi Christoph,

it might be a better approach to reject the Promise. And for the existing code I know it's not that breaking change.

So the `catch` block could look like:

```typescript
  } catch (e) {
    finishStep(false);
    throw e;
  }
```

So we can keep the return type to be `Promise<void>`. There aren't useful information to return.

The caller is responsible to decide whether to log the error or don't.

**Review by jenssimon — CHANGES_REQUESTED** [review]
See https://github.com/jenssimon/sfcc-deploy/pull/1#issuecomment-921648286

**Comment by uschek** [comment]
@jenssimon Updated.

Now it can be used this way:

```js
sfccDeploy(config).catch((error) => {
  // Deployment was not successful
});
```

**Review by jenssimon — APPROVED** [review]

**Comment by jenssimon** [comment]
Yes or what I would prefer:

```typescript
try {
  await sfccDeploy(config);
} catch(error) {
  // Deployment was not successful
}
```

**Pull request merged**
